# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-17 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensionJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.CharField(blank=True, max_length=1000, null=True)),
                ('expression', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('pred_lang_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('pred_comp_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('pred_segm_image', models.CharField(blank=True, max_length=1000, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time')),
            ],
        ),
    ]
